customer:
  auto-create: true
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public_key.pub
tier:
  values: 10000,50000,100000
server:
  timezone: UTC